version: '3.1'
services:
  mongo:
    image: mongo:6.0.3
    container_name: mongoDB
    command: mongod --port 5435
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 5435:5435

  redis:
    image: redis
    container_name: my-redis
    ports:
      - 6379:6379